### PR TITLE
fix(ui-ux): fixed minor UI fixes for portfolio screen

### LINKED ISSUE #3259: After language change, sorting label does not get translated until currency is changed
#### What happened:
After language change, the sorting label does not get translated until the currency is changed

#### What you expected to happen:
As soon as the Language is changed sorting label should be translated

#### How to reproduce it (as minimally and precisely as possible):
Settings > Language > Change Language > Portfolio > Verify the Sorting Labels > Change currency `BTC`/`USD`/`DFI`

#### Anything else we need to know?:
No

### PR DESCRIPTION
**Pull request by fullstackninja864**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
This PR contains fix for following
- On Press reduced opacity of DFI card than other portfolio card
- After language change, sorting label does not get translated until currency is changed
- Action button evenly spaced when theres only 4 buttons
- Text alignment for DFI card 
#### Which issue(s) does this PR fixes?:

Fixes #3259 #3258

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [x] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx [hunk 1]
```diff
@@ -597,14 +598,15 @@ export function PortfolioScreen ({ navigation }: Props): JSX.Element {
...
+  const { language } = useLanguageContext()
   const getDisplayedSortText = useCallback((text: PortfolioSortType): string => {
     if (text === PortfolioSortType.HighestDenominationValue) {
       return highestCurrencyValue
     } else if (text === PortfolioSortType.LowestDenominationValue) {
       return lowestCurrencyValue
     }
     return text
-  }, [props.modifiedDenominationCurrency])
+  }, [props.modifiedDenominationCurrency, language])
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx:609]: Can we check the sorting label again? It remains untranslated when i tested with the publish preview on iOS and android. 

In any case, i think we can remove `useCallback` of getDisplayedSortText, dont think that function is expensive in terms of computation

Comment (kyleleow) [reply mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx:609]: https://user-images.githubusercontent.com/40191153/182805320-c1aa4307-9fd1-45b6-b2ec-861799f71f30.MOV

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx [hunk 2]
```diff
@@ -27,7 +27,7 @@ export function ActionButtons (): JSX.Element {
   return (
     <View testID='action_button_group'>
       <ScrollView
-        contentContainerStyle={tailwind('px-5 mt-8 flex-row')}
+        contentContainerStyle={tailwind('flex flex-row justify-between w-full px-5 mt-8')}
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx:30]: Can you help to test on mobile again? 
- on iOS, the scrolling to the right is not able to see the last button in full
- on android, the action button is not able to scroll horizontally

iOS: https://user-images.githubusercontent.com/40191153/182810805-3656e187-6209-4cf2-abae-f74c5c601863.MP4
android: https://user-images.githubusercontent.com/40191153/182811469-d0f8728b-52e7-43bb-9997-292fad8cb7e6.mp4

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx (hunk 1 above)
Comment (fullstackninja864) [reply mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx:609]: Issue is only with english and German switch (This might be because of different bug). I will remove useCallback for now

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TokenAmountTextV2.tsx [hunk 3]
```diff
@@ -29,7 +29,7 @@ export function TokenAmountTextV2 ({
       renderText={(value) =>
         <View style={tailwind('flex flex-1')}>
           <BalanceTextV2
-            containerStyle={[tailwind('justify-end text-right'), { marginBottom: Platform.OS === 'android' ? 2 : 3 }]}
+            containerStyle={[tailwind('text-sm font-semibold-v2 justify-end text-right mb-1')]}
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TokenAmountTextV2.tsx:32]: Looks fine on ios, but not on android:
image

**Review by kyleleow — APPROVED** [review]

**Review by thedoublejay — APPROVED** [review]
