### PR TITLE
Fix bottom sheet on web 

### LINKED ISSUE #1476: Add/Edit Collateral Bottom Sheet not working in web
#### What happened:
The bottom sheet currently works well with mobile, but since we also have a non-mobile (chrome extension, web), it should also work as expected. 

#### What you expected to happen:
- Bottom sheet should work on web

#### How to reproduce it (as minimally and precisely as possible):
When navigating to: Loans -> Add Token as Collateral -> Select Token to Add -> Select any token -> the web version should still display without crashing

### PR DESCRIPTION
**Pull request by pierregee**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
- This is to allow the bottom sheet to render on non-mobile devices while keeping the ios keyboard to push the UI up when opening

#### Which issue(s) does this PR fixes?:

Fixes #1476

#### Additional comments?:
- There isn’t any web support on the library level as of now: https://github.com/gorhom/react-native-bottom-sheet/issues/11

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

File: mobile-app/app/components/WalletTextInput.tsx [hunk 1]
```diff
@@ -20,12 +29,12 @@ interface IWalletTextInputProps {
   displayFocusStyle?: boolean
   containerStyle?: string
   onBlur?: () => void
+  hasBottomSheet?: boolean
```
Comment (pierregee) [inline mobile-app/app/components/WalletTextInput.tsx:32]: Tried to look into the library to detect if there's a "wrapping" bottom sheet, but it isn't exposed anywhere
