### PR TITLE
`input field` - fix button overflow

### LINKED ISSUE #991: `Send – UI` - `x` and `qr-code` buttons misalign
#### What UI/UX improvements would you like to be implemented: 
Actual: 
• In Send screen, after pasting an address to send, `x` and `qr-code` buttons becomes misaligned

Expected: 
• after pasting an address to send, `x` and `qr-code` buttons should remain in its original position

210930 v0 10 11 - iOS -  Balances - Send - x and qr button misaligned2

#### Why is this needed: 
• Inconsistency in UI

#### Which component/screens does this concern?:
iOS & Android: 
• Send 

#### Anything else we need to know?:

210930 v0 10 11 - iOS -  Balances - Send - x and qr button misaligned

### PR DESCRIPTION
**Pull request by kyleleow**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
- To fix set amount button and clear input button from overflowing the input field container when there are input
- To fix clear input button custom background layer from misaligning when there height of input field changes

#### Which issue(s) does this PR fixes?:

Fixes #991 

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

File: mobile-app/app/components/WalletTextInput.tsx [hunk 1]
```diff
@@ -110,7 +110,10 @@ function ClearButton (props: {onPress?: () => void, testID?: string}): JSX.Eleme
       <ThemedView
         light={tailwind('bg-gray-800')}
         dark={tailwind('bg-gray-100')}
-        style={tailwind('top-2 left-3 rounded-full absolute w-9/12 h-3/6 -z-1', { 'w-5/12': Platform.OS === 'web' })}
+        style={[
+          tailwind('top-2 left-3 rounded-full absolute w-9/12 -z-1', { 'w-5/12': Platform.OS === 'web' }),
+          { height: 16 }
```
Comment (fullstackninja864) [inline mobile-app/app/components/WalletTextInput.tsx:115]: can use `h-4` here as a class

**Review by fullstackninja864 — CHANGES_REQUESTED** [review]

**Review by fullstackninja864 — APPROVED** [review]

**Comment by fullstackninja864** [comment]
LGTM

**Review by thedoublejay — APPROVED** [review]
