### PR TITLE
ui fixes

### LINKED ISSUE #290: `balances` - device with larger fonts breaks layout
#### What happened:
On devices which are using larger fonts, the layout breaks.
#### What you expected to happen:
Should wrap text properly

Larger font on Settings vs Normal font
<div>

</div>

### PR DESCRIPTION
**Pull request by thedoublejay**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
1. Fixed text overflow on Balances Page
2. Fixed animation and text overflow for errors on OceanInterface
3. Fixed disabled button for OceanInterface - Explorer
4. Created Section Title component

#### Which issue(s) does this PR fixes?:

Fixes #290

### CODE REVIEW

File: app/components/SectionTitle.tsx [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+import tailwind from 'tailwind-rn'
+
+export function SectionTitle ({ text, testID }: { text: string, testID: string }): JSX.Element {
+  return (
+    <Text
+      testID={testID}
+      style={[tailwind('p-4 text-xs text-gray-500 font-bold mt-2')]}
+    >
+      {
+        text
```
Comment (fuxingloh) [inline app/components/SectionTitle.tsx:12]: minor suggestion: maybe you could have this as a {props.children} instead?

**Review by fuxingloh — APPROVED** [review]

**Review by ivan-zynesis — APPROVED** [review]

File: app/components/SectionTitle.tsx (hunk 1 above)
Comment (thedoublejay) [reply app/components/SectionTitle.tsx:12]: ah yeah good idea. If we have a section title with info symbol or tooltip, might be useful. I'll do it on next PR
