### PR TITLE
fix(ui-ux): display locked collateral in portfolio

### LINKED ISSUE #2702: `portfolio` - if token is used as 100% collateral. it's not displayed on tokens list
#### What you expected to happen:
If the token is used 100% collateral. It's not displayed on tokens list on portfolio page. Currently, it's only displayed if there's an available balance.

e.g:
If you have 10 ETH, all of it is used as collateral, it will not be displayed on portfolio page. If you remove 1 ETH as collateral, then it will be displayed.

We need to display the token on the list even without any balance as long as it's locked as collateral.

### PR DESCRIPTION
**Pull request by kyleleow**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
- To display locked collateral in portfolio regardless of percentage locked

#### Which issue(s) does this PR fixes?:

Fixes #2702

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [x] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

File: shared/store/wallet.ts [hunk 1]
```diff
@@ -98,16 +95,6 @@ export const setTokenSymbol = (t: AddressToken): WalletToken => {
   }
 }
 
-const associateTokens = (tokens: TokenData[]): AssociatedToken => {
-  const result: AssociatedToken = {}
-  tokens.forEach(token => {
-    if (token.isDAT) {
```
Comment (pierregee) [inline shared/store/wallet.ts:104]: We are filtering out `isDAT` because the API returns multiple displaySymbol and some of it are not the DAT

Here's my 2 cents:
 - If this will be removed, then we need to update `tokenSelectorByDisplaySymbol` to only return `isDAT` or else it would return incorrect ids

- Also if this filtering will be removed on this level, we always have to be mindful when using `allTokens` to always use `isDAT` unless oceanAPI will update it on their end to always filter it out



image

Comment (kyleleow) [reply shared/store/wallet.ts:104]: thanks for the context

Comment (kyleleow) [reply shared/store/wallet.ts:104]: updated

**Review by pierregee — DISMISSED** [review]

**Review by pierregee — DISMISSED** [review]
Issues raised are resolved and tokens with only locked collateral is now displaying

File: mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx [hunk 2]
```diff
@@ -154,6 +154,37 @@ export function BalancesScreen ({ navigation }: Props): JSX.Element {
...
+      return dstTokens
+    }
+
+    const dstTokenSymbols = dstTokens.map(token => token.symbol)
+    lockedTokens.forEach((_lockedBalance, symbol) => {
+      const tokenExist = dstTokenSymbols.includes(symbol)
+      if (!tokenExist) {
+        const tokenData = allTokens.find(token => token.symbol === symbol)
+        if (tokenData !== undefined) {
+          dstTokens.push({
```
[the remark this answers is not in the document]
Comment (kyleleow) [reply mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx]: `Map` doesn't have `reduce()` method, but if you're talking about immutability, i have update to return a new array.

File: mobile-app/app/screens/AppNavigator/screens/Balances/hooks/TokenLockedBalance.ts [hunk 3]
```diff
@@ -15,10 +15,10 @@ export interface LockedBalance {
 
 /**
  *
- * @param symbol optional token symbol
- * @returns Map of all token's locked balance or single object of symbol passed
+ * @param symbol optional token displaySymbol
+ * @returns Map of all token's locked balance or single object of displaySymbol passed
```
Comment (thedoublejay) [inline mobile-app/app/screens/AppNavigator/screens/Balances/hooks/TokenLockedBalance.ts:19]: I think there's a reason why it was kept to Symbol. Might be the API?

Comment (thedoublejay) [reply mobile-app/app/screens/AppNavigator/screens/Balances/hooks/TokenLockedBalance.ts:19]: Can you double check first? Just to ensure we don't cause any regressions

**Review by thedoublejay — CHANGES_REQUESTED** [review]

File: mobile-app/app/screens/AppNavigator/screens/Balances/hooks/TokenLockedBalance.ts (hunk 3 above)
Comment (kyleleow) [reply mobile-app/app/screens/AppNavigator/screens/Balances/hooks/TokenLockedBalance.ts:19]: we kept `symbol` last time because `getTokenPrice()` requires symbol.
If you look at line 41, I am still calling `getTokenPrice()` using `symbol`, that part is unchanged, i only changed the `displaySymbol` to be used as the key for the returned `Map`

I have also cross-checked in mainnet, the number checks out for all of usd, DFI and BTC value of tokens, LPs, and dTokens

**Review by thedoublejay — APPROVED** [review]
