### PR TITLE
fix(core): add custom redirect on back button

### LINKED ISSUE #2680: `add liquidity` - go back to token details screen
#### What UI/UX improvements would you like to be implemented: 
- After entering `add liquidity` screen from `token details` screen, going back should be `token details`, currently it is going back to `DEX` screen

#### Why is this needed:
- UX consistency

#### Which component/screens does this concern?:
- token details
- add liquidity

#### Anything else we need to know?:
- Add liquidity screen and confirm liquidity screen into `BalancesNavigator`

### PR DESCRIPTION
**Pull request by pierregee**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
- Pass necessary params to be able to properly navigate back to TokenDetail screen from AddLiquidity
- Add e2e to make sure `back` is working when origin is Balances screen

#### Which issue(s) does this PR fixes?:

Fixes #2680

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [x] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

File: mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx [hunk 1]
```diff
@@ -100,14 +106,25 @@ export function DexNavigator (): JSX.Element {
       <DexStack.Screen
         component={AddLiquidityScreen}
         name='AddLiquidity'
-        options={{
+        options={({ navigation, route }: StackScreenProps<DexParamList, 'AddLiquidity'>) => ({
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx:109]: Instead of customizing through props, we can add the screen into `BalancesNavigator`

Comment (kyleleow) [reply mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx]: this screen too `ConfirmAddLiquidityScreen`

Comment (pierregee) [reply mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx]: Hmm, back of `ConfirmAddLiquidityScreen` should be to `AddLiquidityScreen`

Comment (kyleleow) [reply mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx]: if you enter through Balance > Token Detail > Add liquidity > Confirm Add Liquidity
what would happen if you go back from Confirm Add Liquidity, will it still reach Token Detail screen?

File: mobile-app/app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx [hunk 2]
```diff
@@ -341,6 +345,59 @@ export function BalancesNavigator (): JSX.Element {
           headerBackTitleVisible: false
         }}
       />
+
+      <BalanceStack.Screen
```
Comment (fullstackninja864) [inline mobile-app/app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx:349]: Dont we have any different approach? instead of adding new routes for Add, confirm Liquidity Screen into balance navigator?

Comment (pierregee) [reply mobile-app/app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx:349]: This was the [first approach ](https://github.com/DeFiCh/wallet/pull/2732/commits/670331166bd060c6c95420abccad1c3ac309da59), but @kyleleow and I felt that this is a better approach

**Review by thedoublejay — APPROVED** [review]
