### PR TITLE
fix(ui-ux): `payback loan` - incorrect error message when clearing input amount

### LINKED ISSUE #2205: `payback loan` - incorrect error message when clearing input amount
#### What happened:
- Tapping clear input button on the amount input field in loan payback screen currently display inaccurate error message

#### What you expected to happen:
- To not display any error message when no input

#### How to reproduce it (as minimally and precisely as possible):
- Go to any loan payback screen > clear amount input field

#### Anything else we need to know?:
IMG_3FBBDA348B80-1

### PR DESCRIPTION
**Pull request by chloezxyy**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
To not display error message when there is no input and have expected css color for text input box of grey instead of red border.

#### Which issue(s) does this PR fixes?:

Fixes #2205

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

File: mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx [hunk 1]
```diff
@@ -196,6 +197,14 @@ export function PaybackLoanScreen ({
       .catch(logger.error)
   }, [])
 
+  useEffect(() => {
+    if (new BigNumber(amountToPay).lte(0) || amountToPay === '') {
+      setZeroInputAmt(false)
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx:202]: Naming logic is kinda counter-intuitive here, `zeroInputAmt` implies that the input amount is zero, but the condition here says otherwise

Also can `zeroInputAmt` be changed into another name so that we are able to instantly differentiate that it is a boolean?

File: mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx [hunk 2]
```diff
@@ -196,6 +197,10 @@ export function PaybackLoanScreen ({
       .catch(logger.error)
   }, [])
 
+  useEffect(() => {
+    return setIsValidInput(new BigNumber(amountToPay).lte(0) || amountToPay === '')
```
Comment (thedoublejay) [inline mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx:201]: Is your naming correct? Valid input should be lte 0?

If yes, maybe we can change amountToPay === '' to isNaN

**Review by thedoublejay — CHANGES_REQUESTED** [review]

**Comment by kyleleow** [comment]
Can you help to add some e2e for this?

File: mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx [hunk 3]
```diff
@@ -276,12 +281,12 @@ export function PaybackLoanScreen ({
...
           testID='payback_input_text'
-          valid={hasSufficientPaymentTokenBalance}
-          {...(!hasSufficientPaymentTokenBalance && {
+          valid={hasSufficientPaymentTokenBalance || isInputEmpty}
+          {...(!hasSufficientPaymentTokenBalance && !isInputEmpty && {
             inlineText: {
               type: 'error',
               text: translate('screens/PaybackLoanScreen', 'Insufficient {{token}} balance to pay the entered amount', { token: selectedPaymentToken.tokenDisplaySymbol })
-            }
+              }
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx:289]: Can revert this line?

File: mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts [hunk 4]
```diff
@@ -350,6 +350,11 @@ context('Wallet - Loans - Payback Loans', () => {
     cy.getByTestID('conversion_info_text').should('not.exist')
   })
 
+  it('should not display warning msg when input is NaN or less than 0', function () {
+    cy.getByTestID('payback_input_text').clear()
```
Comment (kyleleow) [inline mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts:354]: you handled the `NaN` case, but your test title also mention less than 0, want to add a step for that?

**Review by kyleleow — APPROVED** [review]

**Review by thedoublejay — APPROVED** [review]
