### PR TITLE
Fix unable to sign tx

### LINKED ISSUE #522: `transaction authorization` - After entering the passcode to sign a transaction, stuck at that page and transaction doesn't get signed.
#### What happened:

On iOS TestFlight v0.3.2, Playground

1. Send 0.5 `USDT` to another address
1. After entering the passcode to sign a transaction, stuck at that page and the transaction doesn't get signed.

### LINKED ISSUE #541: `transaction authorization` - on open, attempt error message stutters
#### What happened:
When user has an existing attempt and cancelled, re-opening it causes some stutter of the error message. It displays as 2 attempts then changes to last attempt

https://user-images.githubusercontent.com/25013382/129121412-4b442b4b-db43-4089-aa25-fc332bad2fc9.MP4

### PR DESCRIPTION
**Pull request by ivan-zynesis**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
cyclic hook dep causing passcode prompting fail state check

#### Which issue(s) does this PR fixes?:

Fixes #522 
Fixes #541

### CODE REVIEW

File: app/screens/TransactionAuthorization.tsx [hunk 1]
```diff
@@ -80,43 +80,32 @@ export function TransactionAuthorization (): JSX.Element | null {
...
-        // passphrase prompt is meant for authorizing single transaction regardless
-        // caller should not prompt for next transaction before one is completed
-        // proxy the promise, wait for user input
-        PASSPHRASE_PROMISE_PROXY = {
-          resolve, reject
-        }
-        emitEvent('PIN')
-      })
-    }
-  }, [status])
```
Comment (ivan-zynesis) [inline app/screens/TransactionAuthorization.tsx:114]: main issue, although this callback is aware (dep list) of `status` update. However, the instance of `onPrompt` passed/provided do use the initial value.

Adding `onPrompt` as dep list to useEffect will lead to cyclic dep child->parent->child->... infinite re-render.
Have to give up the extra check here.

The status check before start signing/authenticate is the guard to prevent start prompt for pin.

File: app/screens/TransactionAuthorization.tsx [hunk 2]
```diff
@@ -80,43 +80,32 @@ export function TransactionAuthorization (): JSX.Element | null {
...
   const onRetry = useCallback(async (attempts: number) => {
     setIsRetry(true)
-    setPin('')
     setAttemptsRemaining(MAX_PASSCODE_ATTEMPT - attempts)
     await PasscodeAttemptCounter.set(attempts)
-    emitEvent('PIN')
   }, [attemptsRemaining])
 
-  // transaction signing specific callback
-  const onComplete = useCallback(async (dispatch: Dispatch<any>, tx: CTransactionSegWit) => {
```
Comment (ivan-zynesis) [inline app/screens/TransactionAuthorization.tsx:90]: move this single use callback declaration straight into signTx.then

File: app/screens/TransactionAuthorization.tsx [hunk 3]
```diff
@@ -80,43 +80,32 @@ export function TransactionAuthorization (): JSX.Element | null {
...
-      })
-    }
-  }, [status])
-
-  const onSubmitCompletion = (): void => {
+  const onTaskCompletion = (): void => {
     setPin('')
-    emitEvent('IDLE')
     setIsRetry(false)
+    emitEvent('IDLE') // very last step, open up for next task
```
Comment (ivan-zynesis) [inline app/screens/TransactionAuthorization.tsx:108]: the one and only possible IDLE event emitter (except initialization), as the very last step in the `finally` block

**Review by thedoublejay — APPROVED** [review]
