### PR TITLE
`transaction ui` - fixes

### LINKED ISSUE #462: `transaction authorization` - cancel button
#### What happened:
Clicking on cancel button, intermittently loads the screen again. On the code, once onCancel is called, it calls onPrompt that triggers emitEvent('pin') event. Test case for cancel is failing due to this issue, you can refer to this - https://github.com/DeFiCh/wallet/blob/68613513c426a07d80636c5f06390a4d4f857ca9/cypress/integration/functional/wallet/authorization/transactionAuthorization.spec.ts#L14

#### Anything else we need to know?:
/triage accepted
/assign @ivan-zynesis 
/area e2e

### LINKED ISSUE #475: `transaction authorization` - cancel should not reset attempts
#### What happened:

- [ ] Cancelling the transaction prompt resets the attempts. It might be a root cause of brute force attack on pin code as they will get unlimited attempts. Both on transaction and non-transaction prompts.

- [ ] Another issue on transaction prompts, on cancel the error is still displayed there. Does not happen on non transaction ui

### LINKED ISSUE #513: `transaction authorization` - on open, automatic validation
#### What happened:
When signing a transaction, the transaction authorization automatically triggers a validation causing it to close.

https://user-images.githubusercontent.com/25013382/128797650-ec6c73c4-fe6f-40f8-ba54-3e87c338b42b.mp4

### PR DESCRIPTION
**Pull request by thedoublejay**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
1. Fix issues with Transaction UI
2. Fixes #513 - It happens because there's an error on the initial transaction and not on the signing itself. Causing it to auto-retry even without any inputs
3. Fixes #475 - Attempt is recovered from LocalStorage
4. Fixes #462 - Cancelling should work now and not re-trigger
5. Added e2e tests to cover all these scenarios
#### Which issue(s) does this PR fixes?:

Fixes #

### CODE REVIEW

File: app/screens/TransactionAuthorization.tsx [hunk 1]
```diff
@@ -120,49 +142,63 @@ export function TransactionAuthorization (): JSX.Element | null {
...
           })
           .then(async () => {
-            if (invalidPassphrase) {
+            if (status === INVALID_HASH) {
+              setAttemptsRemaining(MAX_PASSCODE_ATTEMPT)
+              await PasscodeAttemptCounter.set(0)
               await clearWallets()
               onUnlinkWallet()
-            } else {
+            } else if (status !== USER_CANCELED) {
```
Comment (ivan-zynesis) [inline app/screens/TransactionAuthorization.tsx:193]: please use the fix in #458 (which is more intuitive, do not have to wait for error preprocess for valid passcode callback)

Comment (thedoublejay) [reply app/screens/TransactionAuthorization.tsx:193]: ah yeah make sense, let me try it locally first

Comment (thedoublejay) [reply app/screens/TransactionAuthorization.tsx]: Updated @ivan-zynesis

**Review by ivan-zynesis — APPROVED** [review]
