### PR TITLE
fix(ui-ux): minor ui fixes

### LINKED ISSUE #3256: Minor UI issues in LW 2.0 designs
#### What happened:

#1 Toggle currency button with odd spacing
#2 these button should be evenly spaced when theres only 4 buttons
#3 wrong icon for external link
#4 check if font size is correct (bottom value should be smaller than top)
#5 filter buttons not full rounded corners
#6 text alignment off
#7 address content alignment off, padding should be 20px
#8 no need for ext link icon here (its already on the card bellow), and address should be full two liners.
#9 spacing should be 12px instead of 8px
#10 learn more about DFI should link to FAQ instead? (edited
#11. the padding of DFI button increases after 1 round of toggling

#### Anything else we need to know?:

Screenshot 2022-08-03 at 3 22 28 PM

Screenshot 2022-08-03 at 3 22 43 PM

Screenshot 2022-08-03 at 3 22 57 PM

Screenshot 2022-08-03 at 3 23 11 PM

Screenshot 2022-08-03 at 3 23 28 PM

Screenshot 2022-08-03 at 3 24 48 PM

### PR DESCRIPTION
**Pull request by siradji**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
Fixes for: 
- Removed redundant external link icon on Wallet modal
- Fixed padding issue on address list item
- Fixed font size issue on tokens details page
- Fixed wrong external link icon on tokens datails pag
#### Which issue(s) does this PR fixes?:

Fixes #3256

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx [hunk 1]
```diff
@@ -372,7 +372,7 @@ function TokenSummary (props: { token: WalletToken, border?: boolean, usdAmount:
             <Icon height={40} width={40} />
           )
         }
-        <View style={tailwind('flex-col ml-2')}>
+        <View style={tailwind('flex-col ml-3')}>
           <ThemedTextV2
             style={tailwind('text-sm font-bold-v2')}
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx:377]: Not in the reported bug, but let's change this to match figma
```suggestion
            style={tailwind('font-bold-v2')}
```

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx [hunk 2]
```diff
@@ -414,7 +414,7 @@ function TokenSummary (props: { token: WalletToken, border?: boolean, usdAmount:
                   displayType='text'
                   renderText={(value) => (
                     <ThemedTextV2
-                      style={tailwind('flex-wrap mr-1 text-sm font-semibold-v2 text-right')}
+                      style={tailwind('flex-wrap mr-1 font-semibold-v2 text-right')}
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx:417]: Not in the reported bug, but let's change this to match figma
```suggestion
                      style={tailwind('flex-wrap font-semibold-v2 text-right')}
```

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetailV2.tsx [hunk 3]
```diff
@@ -162,7 +162,7 @@ export const BottomSheetAddressDetailV2 = (props: BottomSheetAddressDetailProps)
     return (
       <ThemedTouchableOpacityV2
         key={item}
-        style={tailwind('p-4 flex flex-row items-center justify-between border-0 mx-5 rounded-lg-v2 h-20')}
+        style={tailwind('p-5 flex flex-row items-center justify-between border-0 mx-5 rounded-lg-v2 h-20')}
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetailV2.tsx:165]:
```suggestion
        style={tailwind('px-5 py-4.5 flex flex-row items-center justify-between border-0 mx-5 rounded-lg-v2 h-20')}
```

**Comment by kyleleow** [comment]
You missed out item 10

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetailV2.tsx (hunk 3 above)
Comment (siradji) [reply mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetailV2.tsx:165]: @kyleleow, isn't it 20px on the Figma file?

Comment (kyleleow) [reply mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetailV2.tsx:165]: measure from the text, since the text has a taller height

File: mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx [hunk 4]
```diff
@@ -372,9 +372,9 @@ function TokenSummary (props: { token: WalletToken, border?: boolean, usdAmount:
             <Icon height={40} width={40} />
           )
         }
-        <View style={tailwind('flex-col ml-2')}>
+        <View style={tailwind('flex-col ml-3')}>
           <ThemedTextV2
-            style={tailwind('text-sm font-bold-v2')}
+            style={tailwind('font-bold-v2')}
```
Comment (kyleleow) [inline mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx:377]:
```suggestion
            style={tailwind('font-semibold-v2')}
```

**Comment by siradji** [comment]
@kyleleow

**Review by thedoublejay — APPROVED** [review]

**Review by thedoublejay — APPROVED** [review]
