### PR TITLE
links - open on browser 

### LINKED ISSUE #976: `Android - About` - YouTube link inactive
#### What happened:
• YouTube link inactive

#### What you expected to happen:
• Should open YouTube App / direct user to YouTube website via phone' browser

#### How to reproduce it (as minimally and precisely as possible):
About > select `YouTube`

#### Anything else we need to know?:

https://user-images.githubusercontent.com/65014479/135249023-6aaec730-8dec-4937-9ed3-ef2a55ff33e7.mp4

### PR DESCRIPTION
**Pull request by thedoublejay**
#### What kind of PR is this?:

/kind fix

#### Which issue(s) does this PR fixes?:

Fixes #976 

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

File: mobile-app/app/api/linking.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import { Platform } from 'react-native'
+import * as Linking from 'expo-linking'
+import * as WebBrowser from 'expo-web-browser'
+
+export async function openURL (url: string): Promise<void> {
```
Comment (fullstackninja864) [inline mobile-app/app/api/linking.ts:5]: Can we clean this function as 
```
export async function openURL (url: string): Promise<void> {
  if (Platform.OS !== 'android') {
    const supported = await Linking.canOpenURL(url)
    if (supported) {
      return await Linking.openURL(url)
    }
  }
  return await WebBrowser.openBrowserAsync(url)
}

**Review by fullstackninja864 — CHANGES_REQUESTED** [review]

**Review by kyleleow — APPROVED** [review]

**Review by fullstackninja864 — APPROVED** [review]

**Comment by fullstackninja864** [comment]
Looks good to me. lgtm
